# Generated by Django 4.2.5 on 2023-12-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytodolist',
            old_name='email',
            new_name='creator_email',
        ),
        migrations.RenameField(
            model_name='mytodolist',
            old_name='password',
            new_name='task_content',
        ),
        migrations.RenameField(
            model_name='mytodolist',
            old_name='username',
            new_name='task_title',
        ),
    ]
